# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
org.gradle.jvmargs=-Xmx3G
org.gradle.java.home=/usr/lib/jvm/java-25-openjdk
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# Parchment mappings (better parameter names / javadoc)
# https://parchmentmc.org/docs/getting-started
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

# Minecraft / NeoForge versions
# https://projects.neoforged.net/neoforged/neoforge
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.219
loader_version_range=[1,)

## Mod Properties
mod_id=jetlytra
mod_name=Jetlytra
mod_license=All Rights Reserved
mod_version=1.0.0
mod_group_id=pl.siarko.jetlytra

## Dependency versions
geckolib_version=4.7.6

# Optional dependencies
create_version=6.0.9-216
ponder_version = 1.0.82
flywheel_version = 1.0.6
registrate_version = MC1.21-1.3.0+67
jei_file_id=7391682
